version: '3.8'

services:
  svm-microservice:
    build:
      context: ./SVM-microservice
    ports:
      - "5001:5001"
    networks:
      - app_network
    depends_on:
      - vgg-microservice

  vgg-microservice:
    build:
      context: ./VGG-microservice
    ports:
      - "5002:5002"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
